# Generated by Django 5.0.7 on 2025-04-18 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=100)),
                ('contrasena', models.CharField(max_length=100)),
                ('imagen', models.ImageField(upload_to='rostros/')),
            ],
        ),
    ]
